############################################
#### Server
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true



############################################
####  Spring
spring:
  datasource:
    writer:
      jdbc-url: jdbc:postgresql://aurora-dev-p5.cluster-c2as9ee4bg3m.ap-northeast-2.rds.amazonaws.com:5432/contents_mylgdb
      username: postgres
      password: devadmin!
      minimum-idle: 5
      maximum-pool-size: 5
    reader:
      jdbc-url: jdbc:postgresql://aurora-dev-p5.cluster-ro-c2as9ee4bg3m.ap-northeast-2.rds.amazonaws.com:5432/contents_mylgdb
      username: postgres
      password: devadmin!
      minimum-idle: 5
      maximum-pool-size: 5

  jpa:
    database: postgresql
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false

  #### Cache - Redis
  cache:
    type: redis
  redis:
    cluster:
      nodes: ["redis-dev-iptv-dev-msa-01-0001-001.b4rwjf.0001.apn2.cache.amazonaws.com:6379", "redis-dev-iptv-dev-msa-01-0002-001.b4rwjf.0001.apn2.cache.amazonaws.com:6379"]


  # Message Stream - Kafka
  kafka:
    bootstrap-servers: b-1.msk-dev-iptv-msa.66adcz.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-2.msk-dev-iptv-msa.66adcz.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-3.msk-dev-iptv-msa.66adcz.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-4.msk-dev-iptv-msa.66adcz.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-5.msk-dev-iptv-msa.66adcz.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-6.msk-dev-iptv-msa.66adcz.c2.kafka.ap-northeast-2.amazonaws.com:9092



############################################
####  Logging
logging:
  level:
    com.lguplus.fleta: DEBUG
    org.hibernate:
      SQL: DEBUG


############################################
####  Management
management:
  endpoints:
    web:
      exposure:
        include: "*"



############################################
#### Other Domain Application Service
service:
  programming:
    url: http://programming.fleta.com
  searchword:
    url: http://searchword.fleta.com
  settings:
    url: http://settings.fleta.com
  vodlookup:
    url: http://vodlookup.fleta.com
  channel:
    url: http://channel.fleta.com
  subscriber:
    url: http://subscriber.fleta.com



############################################
#### hotvod parameters
hotvod:
  filteringsite:
    dir: /NAS_DATA/web/smartux/iptv/filteringsite/



############################################
#### CTC log server
ctc:
  local:
    path: C:\Temp
  remote:
    - name: CTC1
      host: 127.0.0.1
      port: 22
      username: MACHINE/username1
      password: password1
      path:
        uxHotvodCategory: /C:/Users/username1/ctc/1/UX_HV_CATEGORY/
        uxHotvodCategoryContent: /C:/Users/username1/ctc/1/UX_HV_CATE_CONTENT/
        uxHotvodContent: /C:/Users/username1/ctc/1/UX_HV_CONT/
        uxHotvodContentExtension: /C:/Users/username1/ctc/1/UX_HV_CONT_EXT/
        uxHotvodHitcountLog: /C:/Users/username1/ctc/1/UX_HV_HITCNT_LOG/
        uxHotvodSite: /C:/Users/username1/ctc/1/UX_HV_SITE/
        hdtvAdvertisementInfo: /C:/Users/username1/ctc/1/HDTV_ADS_INFO/
        hdtvAdvertisementInfoLog: /C:/Users/username1/ctc/1/HDTV_ADS_INFO_LOG/
        hdtvAdvertisementMaster: /C:/Users/username1/ctc/1/HDTV_ADS_MASTER/
        hdtvAdvertisementMasterLog: /C:/Users/username1/ctc/1/HDTV_ADS_MASTER_LOG/
    - name: CTC2
      host: 127.0.0.1
      port: 22
      username: MACHINE/username1
      password: password1
      path:
        uxHotvodCategory: ctc/2/UX_HV_CATEGORY
        uxHotvodCategoryContent: ctc/2/UX_HV_CATE_CONTENT
        uxHotvodContent: ctc/2/UX_HV_CONT
        uxHotvodContentExtension: ctc/2/UX_HV_CONT_EXT
        uxHotvodHitcountLog: ctc/2/UX_HV_HITCNT_LOG
        uxHotvodSite: ctc/2/UX_HV_SITE
        hdtvAdvertisementInfo: ctc/2/HDTV_ADS_INFO
        hdtvAdvertisementInfoLog: ctc/2/HDTV_ADS_INFO_LOG
        hdtvAdvertisementMaster: ctc/2/HDTV_ADS_MASTER
        hdtvAdvertisementMasterLog: ctc/2/HDTV_ADS_MASTER_LOG
